---
- hosts: allswitches
  gather_facts: no
  connection: local

  tasks:
  - name: Obtain credentials
    include_vars: secrets.yaml

  - set_fact: mydate="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"

  - name: Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        #authorize: true
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: Run 'show run'
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show run
      #wait_for: result[0] contains IOS
    register: runconfig

  - debug: var=runconfig.stdout_lines

  - name: Save output to backups
    copy:
      content: "{{ runconfig.stdout[0] }}"
      dest: "./backups/show_run_{{ inventory_hostname }}_{{ mydate }}.txt"
